"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";
import { Badge, Button, Card, Empty, Icon, Spinner } from "@/components/ui";
import { mdToHtml } from "@/lib/markdown";
import type { Customer, Product, Proposal } from "@/lib/types";

function fmtDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  } catch {
    return iso;
  }
}

export default function FinalProposalPage() {
  const { id } = useParams<{ id: string }>();
  const [proposal, setProposal] = useState<Proposal | null>(null);
  const [customer, setCustomer] = useState<Customer | null>(null);
  const [product, setProduct] = useState<Product | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    let alive = true;
    api
      .getProposal(id)
      .then(({ proposal, customer, product }) => {
        if (!alive) return;
        setProposal(proposal);
        setCustomer(customer);
        setProduct(product);
      })
      .catch(() => alive && setNotFound(true))
      .finally(() => alive && setLoading(false));
    return () => { alive = false; };
  }, [id]);

  if (loading) return <main className="flex min-h-screen items-center justify-center gap-2 text-muted"><Spinner /> Loading…</main>;
  if (notFound || !proposal) return <main className="flex min-h-screen items-center justify-center"><Card className="p-8"><p className="font-semibold text-fg">Proposal not found</p></Card></main>;

  const draft = proposal.state.proposal_draft;

  return (
    <main className="min-h-screen px-4 py-6">
      <div className="no-print mx-auto mb-6 flex max-w-3xl items-center justify-between">
        <Button href={`/proposals/${id}`} variant="ghost" size="sm"><Icon name="back" size={15} /> Back to workspace</Button>
        <div className="flex items-center gap-3">
          {proposal.status === "approved" ? <Badge tone="ok">✓ Approved</Badge> : <Badge tone="warn">Draft — pending approval</Badge>}
          <Button onClick={() => window.print()} size="sm">🖨 Print / Export PDF</Button>
        </div>
      </div>

      <article className="print-sheet mx-auto max-w-3xl rounded-2xl border border-line bg-[#0d0d12] px-8 py-10 shadow-card sm:px-12 sm:py-14">
        <header className="mb-8">
          <div className="flex items-center justify-between text-[12px] text-muted">
            <span>Prepared by {product ? "the sales team" : ""}</span>
            <span>{fmtDate(proposal.updated_at)}</span>
          </div>
          <div className="my-5 h-px bg-line" />
          <h1 className="text-3xl font-semibold tracking-tight text-fg">Proposal for {customer?.name ?? "your company"}</h1>
          <p className="mt-2 text-sm text-muted">
            {[product?.name, customer?.industry, customer?.size].filter(Boolean).join(" · ")}
          </p>
        </header>

        {draft ? <div className="md" dangerouslySetInnerHTML={{ __html: mdToHtml(draft) }} /> : <Empty title="No draft yet" hint="Run the pipeline in the workspace first." />}

        <footer className="mt-10 border-t border-line pt-4 text-center text-[11px] text-subtle">Generated by PitchPilot</footer>
      </article>
    </main>
  );
}
